version: '3'
services:
  db:
    image: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql

  api_web:
    image: python:3.8
    command: sh -c "pip install django psycopg2-binary && python django_spotify/manage.py runserver 0.0.0.0:8000"
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: django_spotify.settings
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_ANON_USER: ${DJANGO_ANON_USER}
      DJANGO_ANON_PASSWORD: ${DJANGO_ANON_PASSWORD}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    volumes:
      - .:/app
    working_dir: /app

volumes:
  db-data:
