version: '3'
services:
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: ${PGRST_DB_ANON_ROLE}
      PGRST_SERVER_PROXY_URI: "http://127.0.0.1:3000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
        - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
        - db-data:/var/lib/postgresql/data
        - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  swagger:
    image: swaggerapi/swagger-ui
    ports:
        - "8080:8080"
    expose:
        - "8080"
    environment:
        API_URL: http://127.0.0.1:3000/      
volumes:
    db-data:
