version: '3'
services:
  db:
    image: postgres
    ports:
        - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
        - db-data:/var/lib/postgresql/data
        - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
    db-data:
