name: update_content

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev

    - name: Download JSON data
      run: |
        export PYTHONPATH=$PWD
        export API_URL=${{ secrets.API_URL }}
        export DJANGO_ANON_USER=${{ secrets.DJANGO_ANON_USER }}
        export DJANGO_ANON_PASSWORD=${{ secrets.DJANGO_ANON_PASSWORD }}
        pipenv run python3 commands/download_ranking_data.py

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          any::ggplot2 
          any::jsonlite
          any::ggimage
          any::cropcircles
          any::dplyr
          any::tidyr
        
    - name: Generate content
      run: |
        Rscript R/generate_content.R
                
    - name: Commit and push changes
      run: |
        git config --global user.email "${{ secrets.GIT_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_NAME }}"
        git add .
        git commit -m "Auto commit: Update content" || echo "No changes to commit"
        git push
